class UserNotFoundError(Exception):
    pass


class ExistsUser(Exception):
    pass
